source 'http://rubygems.org'

gem 'rails', '3.0.7' #Use with JRuby >=1.6.0
gem 'sinatra', '1.2.3'
gem 'bcrypt-ruby', '2.1.4'
gem 'devise', '1.3.3'
gem 'cancan', '1.6.4'
#Edge RBHive, TODO: Fork Project into SMSI Git Repo.
#gem 'rbhive', :git => 'git://github.com/forward/rbhive.git'
gem 'formtastic', '1.2.3'
gem 'resque', '1.15.0'
gem 'resque-status', '0.2.3'
gem 'resque-scheduler', '2.0.0.d'
gem 'mongrel', '1.1.5'

if defined?(JRUBY_VERSION)
  gem 'trinidad', '1.1.1'
  #TODO: [WARNING] ffi-ncurses breaks windows
  #[WARNING] *** Using highline effectively in JRuby requires installing the ffi-ncurses gem.
  gem 'ffi-ncurses', '0.3.3' #Requires Declaration for Devise in JRuby
  #gem 'jdbc-postgres'
  gem 'activerecord-jdbc-adapter'
  gem 'activerecord-jdbcsqlite3-adapter'
  #gem 'activerecord-jdbcpostgresql-adapter'
  gem 'jruby-openssl', '0.7.3'
  gem 'jruby-rack', '1.0.8'
  gem 'activerecord-jdbcmysql-adapter'
  #gem 'thrift'
  gem 'warbler', '1.3.0'
else
  gem 'sqlite3-ruby', :require => 'sqlite3'
  gem 'mysql2', '0.2.6'
  gem 'SystemTimer', '1.2.1' # doesn't compile in jruby
end

group :development, :test do
  gem 'arel', '2.0.9'
  gem 'rspec-rails', '2.6.1'
  gem 'cucumber-rails', '0.4.1' #0.5.1 has some dependency errors from capybara-1.0.0.beta1
  gem 'capybara'
  gem 'database_cleaner', '0.6.7'
  gem 'webrat', '0.7.3'
  gem 'capistrano', '2.5.21'
end